package br.com.craftonica.electrical.nodal;
public enum DiagnosticCode {
    NETWORK_TOO_LARGE, TERMINAL_LIMIT, BRANCH_LIMIT, MATRIX_LIMIT, NONLINEAR_LIMIT,
    MISSING_REFERENCE, INVALID_COMPONENT_DATA, FLOATING_NODE, SINGULAR_MATRIX,
    ILL_CONDITIONED_MATRIX, RESIDUAL_TOO_LARGE, CONFLICTING_CONSTRAINTS,
    NON_FINITE_VALUE, SHORT_CIRCUIT
}
