package br.com.craftonica.electrical.nodal;
public enum DiagnosticCode {
    NETWORK_TOO_LARGE, TERMINAL_LIMIT, BRANCH_LIMIT, MATRIX_LIMIT, NONLINEAR_LIMIT,
    MISSING_REFERENCE, INVALID_COMPONENT_DATA, FLOATING_NODE, SINGULAR_MATRIX,
    ILL_CONDITIONED_MATRIX, RESIDUAL_TOO_LARGE, CONFLICTING_CONSTRAINTS,
    NON_FINITE_VALUE, POLARITY_INCORRECT, LED_ABOVE_RECOMMENDED_CURRENT,
    LED_OVERCURRENT, SOURCE_OVERCURRENT, POWER_EXCEEDED, SHORT_CIRCUIT,
    NON_CONVERGENT, INCOMPLETE_NETWORK
}
