package br.com.craftonica.electrical.nodal;

public enum SolveStatus { SOLVED, MISSING_REFERENCE, FLOATING_NODE, SINGULAR_MATRIX,
    ILL_CONDITIONED_MATRIX, RESIDUAL_TOO_LARGE, CONFLICTING_CONSTRAINTS, NON_FINITE_VALUE,
    MATRIX_LIMIT }
